### ISSUE TITLE
Pull-Ups on PWM pins

### ISSUE THREAD

**Issue by dross92** [jpjporto/Fan-Controller#1]
Hi,
I am designing a circuit using the MAX31790 and have referenced your design.  I noticed that you wire the fan's PWM pin straight into the MAX's PWMOUT, however the MAX datasheet specifies PWMOUT is an open-drain output so it must be pulled up to Vcc.  Basically, I was wondering if your circuit functioned properly without these pull-ups.
Please let me know.

Thanks,
Drew

**Comment by jpjporto** [comment]
Hi,

The circuit assumes that the fan connected follows the [4-Wire PWM Fan Specs](http://www.formfactors.org/developer%5Cspecs%5C4_Wire_PWM_Spec.pdf), so each fan internally pulls the PWM signal to Vcc.

Best,
Joao

**Comment by dross92** [comment]
OK, thank you!
